name: Publish NuGet Package
on:
  workflow_dispatch:

jobs:
  nuget-approval:
    runs-on: ubuntu-latest
    environment: " nuget-publish-approval"
    steps:
      - name: approve
        shell: bash
        run: echo "Nuget publish approved"
