name: Publish NuGet Package
on:
  workflow_dispatch:

jobs:
  determine-if-publish-necessary:
    runs-on: ubuntu-latest
    outputs:
      publish-necessary: ${{ steps.check.outputs.publish-necessary }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - name: check
        id: check
        shell: bash
        run: |
          result=$(dotnet run --project ./iac/DetermineIfPublishNecessary/DetermineIfPublishNecessary.csproj)
          echo "publish-necessary=true" >> $GITHUB_OUTPUT
      - name: Debug Output
        run: |
          echo Publish necessary: ${{ steps.check.outputs.publish-necessary }}
  nuget-approval:
    runs-on: ubuntu-latest
    environment: "nuget-publish-approval"
    needs: determine-if-publish-necessary
    if: needs.determine-if-publish-necessary.outputs.publish-necessary == 'true'
    steps:
      - name: approve
        shell: bash
        run: echo "Nuget publish approved"
